In [1]:
# Import Libraries

import random
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.metrics import confusion_matrix, classification_report, precision_score

In [2]:
# Import dataset
dataset = pd.read_csv('master.csv')
X = dataset.iloc[:, [1,6]].values
Y = dataset.iloc[:, 2].values

In [3]:
testSizeStr = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]

In [4]:

for i in range(0,9):
    from sklearn.model_selection import train_test_split
    random.seed(i)
    rndint = random.randint(1,50)
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = testSizeStr[i], random_state = rndint)

    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    
    clf = QDA(reg_param = testSizeStr[i])
    clf_fit = clf.fit(X_train, y_train)
    
    pred2=clf_fit.predict(X_test)

    print(confusion_matrix(pred2, y_test))
    print(np.round(accuracy_score(y_test,pred2)*100))
    print(classification_report(y_test, pred2, digits=3))

[[1356  801]
 [  63  562]]
69.0
[[2642 1654]
 [ 139 1129]]
68.0
[[3994 2570]
 [ 203 1579]]
67.0
[[5273 3327]
 [ 285 2243]]
68.0
[[6587 4106]
 [ 380 2837]]
68.0
[[7868 4921]
 [ 462 3441]]
68.0
[[9130 5574]
 [ 609 4161]]
68.0
[[10264  6007]
 [  876  5109]]
69.0
[[11404  6547]
 [ 1111  5976]]
69.0
             precision    recall  f1-score   support

     female      0.635     0.911     0.749     12515
       male      0.843     0.477     0.609     12523

avg / total      0.739     0.694     0.679     25038

